version: "3.9"

services:
  lb:
    image: haproxy:lts-alpine
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./lb/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - blanco-network
  app:
    image: openjdk:17
    ports:
      - 8081:8081
      - 5050:5050
    tty: true
    command: >
      sh -c "
      microdnf install findutils &&
      ./gradlew myBatisGenerator &&
      ./gradlew clean bootRun
      "
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - db
      - lb
    environment:
      DB_URL: jdbc:mysql://db:3306/blanco
    networks:
      - blanco-network
  db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blanco
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - blanco-network
    volumes:
      - ./db/init/initdb.d:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql"
      - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf
    command: "mysqld"

  dbcli:
    image: mysql:8.0.33
    networks:
      - blanco-network
    command: mysql -hdb -uuser -ppassword blanco

  react-app:
    build:
      context: /Users/hirokihosoba/Desktop/dev/blanco/app/src/main/client
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    volumes:
      - /Users/hirokihosoba/Desktop/dev/blanco/app/src/main/client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - blanco-network

networks:
  blanco-network:
    driver: bridge
